### ISSUE TITLE
I know this repo isn't maintained and I don't expect a response, but I swear I'm doing everything right but I just can't get this to work!

### ISSUE THREAD

**Issue by varxnnn** [eeg3/workspaces-portal#29]
I've done everything according to the readme file, I've given enough and pretty loose perms to EVERYTHING so there are no permission related issues. But then again, there are duplicate entries of events and resources in the CloudFormation console, for some reason my UserPool doesn't get configured with the website even though I've correctly set up everything. 

I desperately want to pull this project off, I really want to learn SAM. I do not understand what I'm doing wrong at this point.

**Comment by ALutchko** [comment]
It'd be nice to show logs, error messages etc. 
No, I'm not the author, just passed by.

**Comment by eeg3** [comment]
I haven't tried deploying this in many years, but figured I'd give it a try to see if I can help get you going, at least past the CloudFormation pieces since that seemed to be of most interest. There's a few things that have changed in the many years since this was written:

1. GitHub defaults to `main` instead of `master` so that will need to be changed in the `deploy.json`
2. The `workspace-create` lambda function is actually missing its `package.json` which breaks the build. You can just do an `npm init` to create a blank one and it'll fix it.
3. The Python packages in Ubuntu have been renamed. Instead of `python-pip` and `python-dev`, those need to be changed to `python3-pip` and `python3-dev` within the `buildspec.yaml` file.
4. The nodejs version in `wsportal.json` is no longer supported as a runtime by lambda. Replace the `Runtime` from `nodejs6.10` to `nodejs16.x` in `wsportal.json`.
5. DockerHub didn't use to rate limit so much, so if you run into that blocking you, you may want to override the environment image in Cloud Build: Cloud Build -> Build Projects -> Project -> Edit Environment -> Override image -> Managed image -> Ubuntu -> Standard.

This does not necessarily fix whatever else may have broken in all the years, but it successfully got through the "CloudFormation" section of setup. You'll need to figure out how the rest of the Configuration section may have changed (e.g. API Gateway's setup process is different now, so the steps aren't exactly the same), as well as if any of the code itself needs updating. Hope this gets you going further!

**Comment by varxnnn** [comment]
Thank you for the responses. After a very frustrating week, I've realised that the code needs a few changes for the APIs to be properly integrated with the front end. I will inculcate the changes mentioned by @eeg3. Thank you so much for the response @ALutchko, I apologize for not responding before.
